// <auto-generated />
using System;
using MechLabLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechLabLibrary.Migrations
{
    [DbContext(typeof(MechLabContext))]
    partial class MechLabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MechLabLibrary.Models.MechLabData", b =>
                {
                    b.Property<Guid>("LabID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Eyeshot");

                    b.Property<byte[]>("Image");

                    b.Property<DateTime>("ModifiedTime");

                    b.Property<string>("Name");

                    b.Property<double>("ViewX");

                    b.Property<double>("ViewY");

                    b.HasKey("LabID");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("MechLabLibrary.Models.MechObjectData", b =>
                {
                    b.Property<Guid>("LabID");

                    b.Property<int>("ObjectID");

                    b.Property<double>("M");

                    b.Property<double>("R");

                    b.Property<string>("Type");

                    b.Property<double>("VX");

                    b.Property<double>("VY");

                    b.Property<double>("X");

                    b.Property<double>("Y");

                    b.HasKey("LabID", "ObjectID");

                    b.ToTable("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
